# Generated by Django 2.2.4 on 2019-08-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='subject',
            field=models.CharField(default='TOC', max_length=50),
            preserve_default=False,
        ),
    ]
