# Generated by Django 2.2.4 on 2019-09-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_attendancerecord_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='branch',
            field=models.CharField(choices=[('Information_Technology', 'Information_Technology'), ('Computer_Science_and_ Engineering', 'Computer_Science_and_Engineering'), ('Electronics_and_Electrical_Engineering', 'Electronics_and_Electrical_Engineering'), ('Mining', 'Mining')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='branch',
            field=models.CharField(choices=[('Information_Technology', 'Information_Technology'), ('Computer_Science_and_ Engineering', 'Computer_Science_and_Engineering'), ('Electronics_and_Electrical_Engineering', 'Electronics_and_Electrical_Engineering'), ('Mining', 'Mining')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='branch',
            field=models.CharField(choices=[('Information_Technology', 'Information_Technology'), ('Computer_Science_and_ Engineering', 'Computer_Science_and_Engineering'), ('Electronics_and_Electrical_Engineering', 'Electronics_and_Electrical_Engineering'), ('Mining', 'Mining')], max_length=50),
        ),
    ]
