# Generated by Django 2.2.4 on 2019-09-02 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190902_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 18, 15, 55, 947188)),
        ),
    ]
