# Generated by Django 2.2.4 on 2019-09-02 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20190902_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='branch',
            field=models.CharField(choices=[('Information_Technology', 'Information_Technology'), ('CSE', 'CSE'), ('Electronics_and_Electrical_Engineering', 'Electronics_and_Electrical_Engineering'), ('Mining', 'Mining')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 3, 3, 33, 55, 365052)),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='branch',
            field=models.CharField(choices=[('Information_Technology', 'Information_Technology'), ('CSE', 'CSE'), ('Electronics_and_Electrical_Engineering', 'Electronics_and_Electrical_Engineering'), ('Mining', 'Mining')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='branch',
            field=models.CharField(choices=[('Information_Technology', 'Information_Technology'), ('CSE', 'CSE'), ('Electronics_and_Electrical_Engineering', 'Electronics_and_Electrical_Engineering'), ('Mining', 'Mining')], max_length=50),
        ),
    ]
